### PR TITLE
[HOPSWORKS-3327] Reorder split output

### PR DESCRIPTION
**Pull request by kennethmhc**
changes:
1. Modified python and java client so that all splits' output are features first followed by labels.
2. Minor fix in `getBatchQuery`

### CODE REVIEW

**Review by jimdowling — APPROVED** [review]
Looks good.

**Comment by tdoehmen** [comment]
Looks good to me too, though I didn't take the time to deploy & test it. Same changes should be done for the Java API. Added a note to Jira

**Comment by kennethmhc** [comment]
@tdoehmen I have changed the Java API as well, or which part of the Java API do you mean?

**Comment by tdoehmen** [comment]
It's good to go @kennethmhc feel free to merge it

**Review by tdoehmen — APPROVED** [review]

**Pull request merged**
