### PR TITLE
[HOPSWORKS-3326][Append] Timezone-independent conversion of Hudi Timestamps and Timezone-Sensitive GH-Actions

### PR DESCRIPTION
**Pull request by tdoehmen**
This PR fixes..
- timezone-independent conversion of hudi timestamps
- adds timezone-senstive tests for ubuntu and windows to CI 

JIRA Issue: -

Priority for Review: -

Related PRs: -

**How Has This Been Tested?**

- [x] Unit Tests
- [ ] Integration Tests
- [ ] Manual Tests on VM

**Checklist For The Assigned Reviewer:**

```
- [ ] Checked if merge conflicts with master exist
- [ ] Checked if stylechecks for Java and Python pass
- [ ] Checked if all docstrings were added and/or updated appropriately
- [ ] Ran spellcheck on docstring
- [ ] Checked if guides & concepts need to be updated
- [ ] Checked if naming conventions for parameters and variables were followed
- [ ] Checked if private methods are properly declared and used
- [ ] Checked if hard-to-understand areas of code are commented
- [ ] Checked if tests are effective
- [ ] Built and deployed changes on dev VM and tested manually
- [x] (Checked if all type annotations were added and/or updated appropriately)
```

### CODE REVIEW

**Review by kennethmhc — APPROVED** [review]
LGTM!

**Comment by kennethmhc** [comment]
It seems that a unit test is missing.

**Comment by tdoehmen** [comment]
That's a good point! I'd need to change the python session's timezone for a good test, but the only way I can find to do this, only works on unix, so this would kind of break the tests on windows

> os.environ['TZ'] = 'Europe/London'
> time.tzset()`

Alternative would make an additional CI run with a GH Actions in a different timezone. Then we also woulndn't need addional tests, because the function itself is already covered by some tests.

**Comment by tdoehmen** [comment]
I added actions for local timezones on windows as well as ubuntu

**Pull request merged**
